/*
 * generated by Xtext 2.25.0
 */
package fr.unice.cotedazur.l3ia2023.mycs;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ChartDslStandaloneSetup extends ChartDslStandaloneSetupGenerated {

	public static void doSetup() {
		new ChartDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
