/*
 * generated by Xtext 2.25.0
 */
package fr.unice.cotedazur.l3ia2023.mycs.ide;


/**
 * Use this class to register ide components.
 */
public class ChartDslIdeModule extends AbstractChartDslIdeModule {
}
