/*
 * generated by Xtext 2.25.0
 */
package fr.unice.cotedazur.l3ia2023.mycs.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.unice.cotedazur.l3ia2023.mycs.ChartDslRuntimeModule;
import fr.unice.cotedazur.l3ia2023.mycs.ChartDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ChartDslIdeSetup extends ChartDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ChartDslRuntimeModule(), new ChartDslIdeModule()));
	}
	
}
