/*
 * generated by Xtext 2.25.0
 */
package fr.unice.cotedazur.l3ia2023.mycs.ui;

import com.google.inject.Injector;
import fr.unice.cotedazur.l3ia2023.mycs.ui.internal.MycsActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ChartDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MycsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MycsActivator activator = MycsActivator.getInstance();
		return activator != null ? activator.getInjector(MycsActivator.FR_UNICE_COTEDAZUR_L3IA2023_MYCS_CHARTDSL) : null;
	}

}
