/*
 * generated by Xtext 2.25.0
 */
package fr.unice.cotedazur.l3ia2023.mycs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ChartDslUiModule extends AbstractChartDslUiModule {

	public ChartDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
